### PR TITLE
Change playground cmd in contributing

### PR DESCRIPTION
**Pull request by bidoubiwa**

### CODE REVIEW

**Review by mdubus — COMMENTED** [review]
I still see the command `serve` in the package.json, and no `playground` command 🧐

**Review by mdubus — CHANGES_REQUESTED** [review]
Oh I get it. This is related to #193
There's still the command `yarn serve` inside the Readme, you should edit it 😉

**Comment by bidoubiwa** [comment]
my bad ! I mixed things up

**Review by mdubus — APPROVED** [review]

**Comment by bidoubiwa** [comment]
bors merge

**Pull request merged**
